### ISSUE TITLE
Easier usage of explain

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/exmol#104]
Working through some examples, I've noted the following things:

1. Descriptor type should have a default - maybe MACCS since the plots will show-up
2. Maybe we should only save SVGs, rather than return unless prompted
3. We should do string comparison for descriptor types using lowercase strings, so that `classic` and `Classic` and `ecfp` are valid.
4. We probably shouldn't save without a filename - it is unexpected

**Comment by whitead** [comment]
4 - Maybe, I feel like it's rare that someone wants to have a default filename. What is more likely is someone doesn't realize it's saving. I guess up to you, but I didn't realize it was saving to a file but if it gave an error if no filename was given I would find out immediately.

**Comment by hgandhi2411** [comment]
4 - Alright, if we want saving to be default behavior (as in 2) then we can make filename a required argument I guess.
