### ISSUE TITLE
run_STONED couldn't generate SMILES after 30 minutes

### ISSUE THREAD

**Issue by qcampbel** [ur-whitelab/exmol#121]
For certain SMILES, `run_STONED()` failed to generate after running for so long. So far, one SMILES known to cause such issue is 

`[Na+].[Na+].[Na+].[Na+].[Na+].[O-][S](=O)(=O)OCC[S](=O)(=O)c1cccc(Nc2nc(Cl)nc(Nc3cc(cc4C=C(\C(=N/Nc5ccc6c(cccc6[S]([O-])(=O)=O)c5[S]([O-])(=O)=O)C(=O)c34)[S]([O-])(=O)=O)[S]([O-])(=O)=O)n2)c1`

Here is how I use the function: `exmol.run_stoned(smiles, num_samples=10, max_mutations=1)`.

**Comment by qcampbel** [comment]
More SMILES:
```
[Na+].[Na+].[Na+].[Na+].[Na+].[O-][S](=O)(=O)OCC[S](=O)(=O)c1cccc(Nc2nc(Cl)nc(Nc3cc(cc4C=C(\C(=N/Nc5ccc6c(cccc6[S]([O-])(=O)=O)c5[S]([O-])(=O)=O)C(=O)c34)[S]([O-])(=O)=O)[S]([O-])(=O)=O)n2)c1
[Na+].[Na+].[Na+].[Na+].NC(=O)Nc1cc(Nc2nc(Cl)nc(Nc3cccc(c3)[S](=O)(=O)CCO[S]([O-])(=O)=O)n2)ccc1N=Nc4cc5c(cc(cc5[S]([O-])(=O)=O)[S]([O-])(=O)=O)cc4[S]([O-])(=O)=O
[Na+].[Na+].CCCCCCCCCCCCNc1nc(Cl)nc(Nc2ccc3c(O)c(N=Nc4ccc(cc4)N=Nc5ccc(cc5)[S]([O-])(=O)=O)c(cc3c2)[S]([O-])(=O)=O)n1
[Na+].[Na+].Cc1ccc(Nc2ccc(Nc3ccc(C)cc3[S]([O-])(=O)=O)c4C(=O)c5ccccc5C(=O)c24)c(c1)[S]([O-])(=O)=O
[O--].[O--].[O--].[O--].[O--].[O--].[O--].[O--].[O--].[Al+3].[Al+3].[Mo].[Mo]
[Na+].[Na+].CC1=NN(C(=O)C1N=Nc2ccc(c3ccc(cc3[S]([O-])(=O)=O)N=NC4C(=NN(C4=O)c5ccccc5)C)c(c2)[S]([O-])(=O)=O)c6ccccc6
[Na+].[Na+].[O-][S](=O)(=O)c1ccc(N\N=C\2C=CC(=O)C(=N/Nc3ccc(c4ccccc34)[S]([O-])(=O)=O)\C2=O)c5ccccc15
```

**Comment by whitead** [comment]
@qcampbel as a first step - I think you may need to remove the ions. Try splitting your records and taking largest component. For example:

```py
def largest_mol(smiles):
  ss = smiles.split('.')
  ss.sort(key = lambda a: len(a))
  return ss[-1]
```

but we'll work in improving that!

**Comment by whitead** [comment]
We need to make sure in the STONED method we throw an error if there are multiple components I think.
