### ISSUE TITLE
STONED implementation adds nitrogen

### ISSUE THREAD

**Issue by TheGoldstone** [ur-whitelab/exmol#139]
Dear Maintainers,

I am currently working with your implementation of the mmace algorithm and applied it to a model and a dataset that only contains carbon and oxygen atoms. Unfortunately, the algorithm returns an error in some cases because the STONED algorithm proposes molecules containing nitrogen, which cannot be passed to the GNN I am working with. This happens despite explicitly excluding nitrogen tokens from the alphabet.

While looking for the reason for this problem I discovered that SELFIES uses nitrogen tokens for these molecules that do not correspond to a nitrogen present in the molecule but denote a branch length if lead by a branch token (cf. [my comment in the SELFIES github project](https://github.com/aspuru-guzik-group/selfies/issues/102#issuecomment-1560120482)). I presume that STONED manipulates these molecules in such a way that nitrogen sometimes remains without a leading branch token, causing the molecule to keep the nitrogen during decoding.

Thank you very much, I hope to hear from you soon!

**Comment by whitead** [comment]
Thanks - yup, very good insight! We should add a filter to the STONED method to check for the decoded SMILES.
