### ISSUE TITLE
Target molecule frequently on the edge of sample space visualization

### ISSUE THREAD

**Issue by adamoyoung** [ur-whitelab/exmol#19]
In your example provided in the code, the target molecule is on the edge of the sampled distribution (in the PCA plot). I also find this happens very frequently with my experiments on my model. I think this suggests that the sampling produces molecules that are not evenly distributed around the target. I just want to verify that this is a property of the STONED sampling algorithm, and not an artifact of the visualization code (which it does not seem to be). I've attached an example of my own, for both "narrow" and "medium" presets.

preset="narrow", nmols=10

![explain_narrow_0 05_10](https://user-images.githubusercontent.com/22357382/130283213-60278cb2-4820-42d3-a78d-3f64ace9d52c.png)

preset="medium", nmols=10

![explain_medium_0 05_10](https://user-images.githubusercontent.com/22357382/130283236-7c4be9e1-d5ab-4e3a-bdcb-1e1f391d9f69.png)

**Comment by whitead** [comment]
@adamoyoung! I think this is more of a visualization artifact. We use distance from base/target to make the plot, so by definition the base is at origin. Great point though, we should add a note to doc/paper about this.

**Comment by adamoyoung** [comment]
Oh I see, I misunderstood the code! Thank you for the clarification.

**Comment by whitead** [comment]
Closed by d73b9aece02f5d12a9e6f9d51d36ae772160b8a3
