### ISSUE TITLE
CODEX Example

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/exmol#61]
While messing around with CODEX, I noticed it wants to compute ECFP4 fingerprints using a different method and this gives slightly different similarities. @geemi725 could you double-check the ECFP4 implementation we have is correct, or is the CODEX one correct?

![image](https://user-images.githubusercontent.com/908389/143046115-faabc4eb-7251-43fc-80fd-95069595dbc2.png)

**Comment by geemi725** [comment]
@whitead this is the [reason](https://www.rdkit.org/docs/GettingStartedInPython.html). Not sure how to pick "what's the best" though. 

<img width="831" alt="Screen Shot 2021-11-23 at 10 11 04 AM" src="https://user-images.githubusercontent.com/49410838/143050474-98029c75-715c-4c64-8871-50b6b65dc02c.png">

**Comment by geemi725** [comment]
@whitead  also codex is taking `1-similarity` with the bit vectors but the output must be similarity, not distance?

**Comment by whitead** [comment]
So which is more accepted?

**Comment by geemi725** [comment]
My understanding is that Morgan FPs by default uses the counts. If we use bit vectors we will be losing info pertaining to the counts. But I have seen bitvectors used more commonly (in the past few weeks).

**Comment by geemi725** [comment]
For future references: Visualizing which atoms contribute to similarity between two molecules. 
<img width="853" alt="Screen Shot 2021-11-23 at 10 55 43 AM" src="https://user-images.githubusercontent.com/49410838/143058270-ba918dec-eddb-42bf-96de-e6428ad5009e.png">

**Comment by whitead** [comment]
Interesting, maybe we could use that for @navneeth3005's project
