### ISSUE TITLE
Error while plotting counterfactuals using plot_cf() 

### ISSUE THREAD

**Issue by hgandhi2411** [ur-whitelab/exmol#72]
`plot_cf()` function errors out with the following error. This behavior is also consistent across all notebooks in `paper/`.

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-b6c8ed26216e> in <module>
      1 fkw = {"figsize": (8, 6)}
      2 mpl.rc("axes", titlesize=12)
----> 3 exmol.plot_cf(exps, figure_kwargs=fkw, mol_size=(450, 400), nrows=1)
      4 
      5 plt.savefig("rf-simple.png", dpi=180)

/gpfs/fs2/scratch/hgandhi/exmol/exmol/exmol.py in plot_cf(exps, fig, figure_kwargs, mol_size, mol_fontsize, nrows, ncols)
    682         title += f"\nf(x) = {e.yhat:.3f}"
    683         axs[i].set_title(title)
--> 684         axs[i].imshow(np.asarray(img), gid=f"rdkit-img-{i}")
    685         axs[i].axis("off")
    686     for j in range(i, C * R):

~/.local/lib/python3.7/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1359     def inner(ax, *args, data=None, **kwargs):
   1360         if data is None:
-> 1361             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1362 
   1363         bound = new_sig.bind(ax, *args, **kwargs)

~/.local/lib/python3.7/site-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, filternorm, filterrad, resample, url, **kwargs)
   5607                               resample=resample, **kwargs)
   5608 
-> 5609         im.set_data(X)
   5610         im.set_alpha(alpha)
   5611         if im.get_clip_path() is None:

~/.local/lib/python3.7/site-packages/matplotlib/image.py in set_data(self, A)
    699                 not np.can_cast(self._A.dtype, float, "same_kind")):
    700             raise TypeError("Image data of dtype {} cannot be converted to "
--> 701                             "float".format(self._A.dtype))
    702 
    703         if self._A.ndim == 3 and self._A.shape[-1] == 1:

TypeError: Image data of dtype <U14622 cannot be converted to float
```

**Comment by whitead** [comment]
@geemi725 this looks like a matplotlib version problem - maybe we need to set a specific version?

**Comment by whitead** [comment]
@hgandhi2411 I'm unable to reproduce this in the latest version. It might be something with your rdkit version or PIL version - I'm not sure.

 It looks like a problem in creating the images. Can you try running [this function](https://github.com/ur-whitelab/exmol/blob/929cb01ff47e64feabfc2184467c17e13c693443/exmol/plot_utils.py#L110) and checking that you're able to get molecule images.

**Comment by hgandhi2411** [comment]
@whitead I am able to get images from `_mol_diff`. 

I investigated a bit and seems like this issue arises because I specify `svg=True` [here](https://github.com/ur-whitelab/exmol/blob/929cb01ff47e64feabfc2184467c17e13c693443/exmol/exmol.py#L567). `plt.imshow()` takes floats, and `np.array(imgs, dtype=float)` cannot convert the svg text to floats.

 When I use `plot_cf()` as is, the image quality is very poor. 
![image](https://user-images.githubusercontent.com/22055417/152001157-06071a51-1ed0-4bbf-af63-bc472d61ecde.png)

**Comment by whitead** [comment]
Can you double-check your line? I can't see an `svg` argument there

**Comment by hgandhi2411** [comment]
In this [line](https://github.com/ur-whitelab/exmol/blob/929cb01ff47e64feabfc2184467c17e13c693443/exmol/exmol.py#L567), the `_mol_images()` function has an optional `svg` argument (default=False). `plot_cf()` uses the default, so you don't see it there. I was seeing the above error because I tried to use `svg=True`.

**Comment by hgandhi2411** [comment]
Closing this issue because `plot_cf()` works fine. My error was because I tried to change the function to get a better quality image.
