### ISSUE TITLE
pypi figures

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/exmol#87]
@hgandhi2411 you need to follow the style of the other figures in README file to get them to render on [pypi homepage. ](https://pypi.org/project/exmol/2.0.0.dev1/)

**Comment by hgandhi2411** [comment]
The figure links and github badges on [pypi homepage](https://pypi.org/project/exmol/2.0.0.dev1/) are still broken

**Comment by whitead** [comment]
@hgandhi2411 It's because I haven't done a new release. We can wait to latest release to close

**Comment by whitead** [comment]
@hgandhi2411 Also, we have complexity in one of the figures. Should remove that, since we took it out of our list.
