### ISSUE TITLE
The module 'exmol' has no attribute 'lime_explain'

### ISSUE THREAD

**Issue by andresilvapimentel** [ur-whitelab/exmol#91]
In the notebook RF-lime.ipynb, the command

exmol.lime_explain(space, descriptor_type=descriptor_type)

gives a error module 'exmol' has no attribute 'lime_explain'

Please, let me know how to fix this error. Thanks.

**Comment by whitead** [comment]
`lime_explain` is available in the pre-release version. Use this command to install/upgrade it: `pip install --pre --upgrade exmol`

**Comment by andresilvapimentel** [comment]
It worked. Thanks.
Another question.... How can I plot the image ECFP.svg using the notebook RF-lime.ipynb?

I used descriptor_type = "ECFP" but the image is different from the image used in the https://github.com/ur-whitelab/exmol main page.
It shows up with no substructures and no structure in the right. The y-axis in the figure shows up many numbers only (no substructures) .

**Comment by whitead** [comment]
@hgandhi2411 may answer better here, but I believe to display SVGs you need to use the command `skunk.display(svg)` by importing the skunk package `import skunk`. Also, the README page results are from the other notebook (RNN) I believe so you may not get the same results. I put the code from the other notebook below on how to plot the explanations:

```
svg = exmol.plot_descriptors(samples, descriptor_type='ECFP')
skunk.display(svg)
```

**Comment by hgandhi2411** [comment]
@andresilvapimentel use `exmol.plot_descriptors()` function as shown by @whitead to get descriptor plots. RF-lime.ipynb was used to create figure 3 in the paper and contains code only for that.
